{{- if and (eq .Values.database.mode "sqlite") .Values.database.sqlite.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todolist.fullname" . }}-data
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.database.sqlite.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  {{- if .Values.database.sqlite.persistence.storageClass }}
  storageClassName: {{ .Values.database.sqlite.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.sqlite.persistence.size }}
{{- end }}
