apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todolist.secretName" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
type: Opaque
stringData:
  session-secret: {{ .Values.session.secret | quote }}
  {{- if or (eq .Values.database.mode "bundled") (eq .Values.database.mode "external") }}
  db-dsn: {{ include "todolist.databaseDSNWithPassword" . | quote }}
  {{- end }}
  {{- if eq .Values.auth.mode "oidc" }}
  oidc-client-secret: {{ .Values.auth.oidc.clientSecret | quote }}
  {{- end }}
